use crate::proxy_function;
use windows_sys::Win32::Foundation::*;
use windows_sys::Win32::System::SystemServices::*;
use windows_sys::Win32::System::LibraryLoader::*;

proxy_function!("version.dll", GetFileVersionInfoA, (filename: LPCSTR, handle: DWORD, len: DWORD, data: LPVOID), BOOL, FALSE);
proxy_function!("version.dll", GetFileVersionInfoSizeA, (filename: LPCSTR, handle: LPDWORD), DWORD, 0);
proxy_function!("version.dll", GetFileVersionInfoW, (filename: LPCWSTR, handle: DWORD, len: DWORD, data: LPVOID), BOOL, FALSE);
proxy_function!("version.dll", GetFileVersionInfoSizeW, (filename: LPCWSTR, handle: LPDWORD), DWORD, 0);
proxy_function!("version.dll", VerQueryValueA, (block: LPVOID, sub_block: LPCSTR, buffer: *mut LPVOID, len: PUINT), BOOL, FALSE);
proxy_function!("version.dll", VerQueryValueW, (block: LPVOID, sub_block: LPCWSTR, buffer: *mut LPVOID, len: PUINT), BOOL, FALSE);
proxy_function!("version.dll", GetFileVersionInfoExA, (flags: DWORD, filename: LPCSTR, handle: DWORD, len: DWORD, data: LPVOID), BOOL, fallback: GetFileVersionInfoA(filename, handle, len, data));
proxy_function!("version.dll", GetFileVersionInfoExW, (flags: DWORD, filename: LPCWSTR, handle: DWORD, len: DWORD, data: LPVOID), BOOL, fallback: GetFileVersionInfoW(filename, handle, len, data));
proxy_function!("version.dll", GetFileVersionInfoSizeExA, (flags: DWORD, filename: LPCSTR, handle: LPDWORD), DWORD, fallback: GetFileVersionInfoSizeA(filename, handle));
proxy_function!("version.dll", GetFileVersionInfoSizeExW, (flags: DWORD, filename: LPCWSTR, handle: LPDWORD), DWORD, fallback: GetFileVersionInfoSizeW(filename, handle));
proxy_function!("version.dll", VerFindFileA, (flags: DWORD, filename: LPCSTR, win_dir: LPCSTR, app_dir: LPCSTR, cur_dir: LPSTR, cur_dir_len: PUINT, dest_dir: LPSTR, dest_dir_len: PUINT), DWORD, 0x0001);
proxy_function!("version.dll", VerFindFileW, (flags: DWORD, filename: LPCWSTR, win_dir: LPCWSTR, app_dir: LPCWSTR, cur_dir: LPWSTR, cur_dir_len: PUINT, dest_dir: LPWSTR, dest_dir_len: PUINT), DWORD, 0x0001);
proxy_function!("version.dll", VerInstallFileA, (flags: DWORD, src_filename: LPCSTR, dest_filename: LPCSTR, src_dir: LPCSTR, dest_dir: LPCSTR, cur_dir: LPCSTR, tmp_file: LPSTR, tmp_file_len: PUINT), DWORD, 0x0001);
proxy_function!("version.dll", VerInstallFileW, (flags: DWORD, src_filename: LPCWSTR, dest_filename: LPCWSTR, src_dir: LPCWSTR, dest_dir: LPCWSTR, cur_dir: LPCWSTR, tmp_file: LPWSTR, tmp_file_len: PUINT), DWORD, 0x0001);
proxy_function!("version.dll", VerLanguageNameA, (lang: DWORD, lang_name: LPSTR, lang_len: DWORD), DWORD, 0);
proxy_function!("version.dll", VerLanguageNameW, (lang: DWORD, lang_name: LPWSTR, lang_len: DWORD), DWORD, 0);
proxy_function!("version.dll", GetFileVersionInfoByHandle, (file: i32, filename: LPSTR, handle: DWORD, len: DWORD, data: LPVOID), DWORD, 0);
